### ISSUE TITLE
フォントにPlexを追加する

### ISSUE THREAD

**Issue by ymnder** [zk-phi/MEGAMOJI#113]
IBMが新たに公開した[Plex](https://www.ibm.com/plex/)という和文ゴシック体のフォントを追加したいです。
小さい絵文字でも潰れずに表示できそうです。

ライセンスは `SIL OPEN FONT LICENSE Version 1.1` で、既に導入されている[Noto Sans JP](https://fonts.google.com/specimen/Noto+Sans+JP?preview.text=&preview.text_type=custom&subset=japanese)と同様のライセンスです。
https://github.com/IBM/plex/blob/master/IBM-Plex-Sans-JP/fonts/complete/woff/hinted/IBMPlexSansJP-Regular.woff

**Comment by zk-phi** [comment]
これな〜〜〜〜
シンプルなゴシック体なので入れるとしたら M+ と入れ替えかなと思うんだけど、丸ゴがないのがなーって思ってる
