### ISSUE TITLE
画像ファイルのサイズ

### ISSUE THREAD

**Issue by misteltein** [zk-phi/MEGAMOJI#15]
面白いツールをありがとうございます。
画像を元に生成して、登録をこころみましたが、
Your file must be less than 64KB in size.
となってしまい、slack emoji に登録できませんでした。
できれば、64 KB以下になるように自動的に圧縮して軽量化できるようにしていただけると
もっと使いやすくなると思います。
ご検討よろしくお願い致します。

**Comment by zk-phi** [comment]
静止画ですか？ :eyes:

**Comment by misteltein** [comment]
そうです

**Comment by zk-phi** [comment]
なるほどー。ちょっと考えてみます :eyes:
ありがとうございます！

**Comment by zk-phi** [comment]
遅くなりましたが実装しました :+1:

**Comment by misteltein** [comment]
ありがとうございました(👁👄👁)✌️
