### ISSUE TITLE
画像のサイズ

### ISSUE THREAD

**Issue by nerixim** [zk-phi/MEGAMOJI#16]
素敵な、治安の悪いSlack Emojiジェネレーターありがとうございます🔞

主に文字列から作成してきて今までとあるサイト（http://www.mojimaru.com/mojiga/ ）を使ってましたが、全然イケてないということでこちらに目をつけました。
こちらで文字列から生成しようとするとサイズが256x256になるのでリサイズの手間がかかってしまいます。
こちらからPRを出したいと思います。
よろしくお願いします。

**Comment by zk-phi** [comment]
MEGAMOJI で生成した画像は、静止画で 128x128、アニメgif で 64x64 になるように実装しているはずなのですが、だめそうでしょうか…？

**Comment by nerixim** [comment]
失礼しました。
プレビューのところを見ていましたmm
