### ISSUE TITLE
「俺」（ゴシック/極太）のアウトラインにトゲが生える

### ISSUE THREAD

**Issue by Phroneris** [zk-phi/MEGAMOJI#210]
![ゴシック／極太](https://user-images.githubusercontent.com/9891867/155735637-d15ff852-acaa-4a41-ab56-e64962484d6c.png)

にんべんの上にトゲが生えます。

設定は次の通りです。

- フォント：ゴシック/極太
- テキスト：`俺`
- 色：プリセットの黄色（#FFDA00）
- アウトライン：プリセットの黒（#000000）
- 効果をつける：（特に無し）

「俺」以外にも、同条件では「僕」「黎」「點」「蛾」などの字で様々なトゲが生えます。
また、「ゴシック/極太」以外のフォントでも生えるものは生えます。
閲覧環境はWindows、Chromeです。

`miterLimit` プロパティとやらで解決するかもしれません。
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/miterLimit

**Comment by zk-phi** [comment]
これ直せないものと思って諦めてました :pray:
おっしゃる通り `miterLImit` で解決しました、ありがとうございます！

**Comment by Phroneris** [comment]
ご対応ありがとうございました。

ものすごく今更のお節介ですが、コミットやPRのメッセージを書く際に ["fix" 等の特定のキーワード](https://qiita.com/maeda_t/items/d9ef98bf651bd491b16d)をIssue番号と組み合わせて使うと、GitHub上のIssueとコミットを関連付けた上で自動Closeできます。
例えばこちらのコミット→ https://github.com/Phroneris/ReaperJPN-Phroneris/commit/a6d480fdc46019617900d6c583f8cd835014f298 では、1行目に何をしたかを書き、2行目を[Gitのしきたり](https://qiita.com/yu_suke1994/items/29625ad905a5dc5df6c0)で空行にして、3行目に `Fix #番号` と書いて関連付け＆自動Closeを発動させています。

参考になれば幸いです。
