### ISSUE TITLE
[バグレポート] テキスト>詳細オプション>色の変更でクラッシュする

### ISSUE THREAD

**Issue by yKicchan** [zk-phi/MEGAMOJI#242]
## 現象

<img width="650" alt="スクリーンショット 2022-05-28 7 39 59" src="https://user-images.githubusercontent.com/27273218/170797245-4a53f3b0-4785-4273-abe1-ddbf2dad7b7c.png">

## 再現手順

1. なんでもいいので文字を入力
2. サンプル表示
3. 「効果を付ける」からアニメーションや特殊効果を付与(アニメーションgifにするとクラッシュまで早くなりました)
4. テキスト設定に戻り「詳細オプション」からカラーピッカーで色を変更(ぐるぐる色変えると特にクラッシュまで早いです)
5. 上記画像の通りクラッシュ後のページが表示される

## 経緯

アニメーションを設定して、グラデーションやコントラストの色調整(目まぐるしく色を変えたりはせず、ぽちぽちと触っていただけ)をしていたらクラッシュし、軽く手順を調べたところ色の変更が複数リアルタイムに反映されることから処理が重くなりクラッシュしているようでした。

<img width="578" alt="スクリーンショット 2022-05-28 7 46 59" src="https://user-images.githubusercontent.com/27273218/170797742-f6361162-2363-4fdf-aa5c-984119bc4df8.png">

## 謝辞

楽しいツールを作ってくださってありがとうございます！
いつも利用させていただいています！

**Comment by zk-phi** [comment]
ありがとうございます :pray:

おっしゃる通り、パラメータを少しでもいじるたびに絵文字を生成しなおしているので、ドラッグで設定するタイプのパラメータは実はかなり負荷高いのですよね…w

ぱっと思いつく対策で：

1. 絵文字を非同期で生成して、前の絵文字が生成中の間は次の絵文字の生成を始めない
2. タイマーで適当に間引く (「最大でも１秒に n 回しか生成しない」)

があるかなーと思っていますが、 1. をやるにはブラウザの OffscreenCanvas 対応 https://developer.mozilla.org/ja/docs/Web/API/OffscreenCanvas#browser_compatibility が進む必要がありそうなのが悩みです。

cf. https://scrapbox.io/MEGAMOJI/%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88%E7%B5%B5%E6%96%87%E5%AD%97%E3%81%AE%E7%94%9F%E6%88%90%E3%81%8C%E9%9D%9E%E5%90%8C%E6%9C%9F%E3%81%98%E3%82%83%E3%81%AA%E3%81%84%EF%BC%86%E3%81%A1%E3%82%87%E3%81%A3%E3%81%A8%E9%81%85%E3%81%84%E5%95%8F%E9%A1%8C

**Comment by zk-phi** [comment]
gif エンコーダーをリプレースして、メモリリーク問題が解決したのでクラッシュはしなくなりました👏

ただ文字から画像への変換が同期的で、タスクが詰まって重くなってしまう問題は解決していないのでこの issue は残しておきます

**Comment by zk-phi** [comment]
文字から画像への変換も、タイマーで間引いて負荷を落とすことで応急措置したので、ほぼほぼ快適に使えるようになったと思います :pray:
