### ISSUE TITLE
Images rendered onto a white background

### ISSUE THREAD

**Issue by Fauntleroy** [zk-phi/MEGAMOJI#25]
Even if my source image has a transparent background, the resulting GIF is rendered on white. If we could find a way to render these GIFs onto a (mostly) transparent background, the emojis would be useful in applications where the background is not always white (like Discord, or perhaps future versions of Slack).

Original
![lego_angry_minifig](https://user-images.githubusercontent.com/507047/45442876-120d6a80-b678-11e8-9ba4-86bdf7c465b0.png)

Processed
![lego_angry_rattle](https://user-images.githubusercontent.com/507047/45442887-18034b80-b678-11e8-873f-7eab384569a3.gif)

**Comment by zk-phi** [comment]
Thanks for sharing ideas !
Unfortunately, animated GIF seems not supporting transparent background (as far as I know) ...

**Comment by zk-phi** [comment]
Forked the jsgif lib and add an experimental implementation of transparent-animated-gif. Now the feature is available in the `+ その他` menu.
