### ISSUE TITLE
絵文字がレンダリングできなくなっている

### ISSUE THREAD

**Issue by k725** [zk-phi/MEGAMOJI#282]
いつも治安の悪い絵文字で楽しんでいます。

これまで絵文字がレンダリングできたようですが、レンダリングできなくなってしまっているようです。

OS: macOS 12.6.1 (en-US), Windows 11 (en-US)
Chrome: 108.0.5359.94
Safari: 16.1

macOS
![image](https://user-images.githubusercontent.com/3895461/206167234-e5ae9504-0dbd-42f0-a9dd-e6295cb6db90.png)

Windows
![image](https://user-images.githubusercontent.com/3895461/206168403-05386efc-ca56-4f20-bce5-6182c9feb82c.png)

**Comment by zk-phi** [comment]
報告ありがとうございます🙏
最近やった内部実装の改善が原因になっていそうだったので、いったん元に戻す対応をしてみました。
