### ISSUE TITLE
効果をつけるタブはオプション機能として扱いたい

### ISSUE THREAD

**Issue by ymnder** [zk-phi/MEGAMOJI#30]
現在MEGAMOJIは4つのタブから構成されていますが、すべての機能が同じタブで扱われていることにより情報構造が分かりにくいように思います。

`テキストから作る・ファイルから選ぶ・パーツから選ぶ`
の3機能は絵文字をcreate / importする機能で
`効果をつける`
は3機能のoutputをemphasizeする機能であると分類できます。

UIUXを改善するため次の修正を行いたいです。

### 案①タブにアイコンをつける
現在 `効果をつける` タブだけ★のアイコンがついています。
他のタブにもそれぞれ、createを示すようなアイコンを付与します。
ref: https://material.io/resources/icons/?icon=create&style=sharp

![add-icon](https://user-images.githubusercontent.com/7427558/95649656-9366ae00-0b19-11eb-9965-0434adba6277.png)

### 案②結果の下に遷移ボタンを置く
結果が表示されるカードの下に `効果をつける` タブを置きます。
結果を見た後に移動するフローがより簡便になります。

![add-effect](https://user-images.githubusercontent.com/7427558/95649786-459e7580-0b1a-11eb-972b-871f88f5e6e8.png)

### 案③3機能をポップアップとして表示する
`効果をつける`をメイン機能とみなした強い変更です。
最初に必ずcreate / importを行ってもらい、じっくり効果をつけてもらうという流れになります。

**Comment by zk-phi** [comment]
案②の方向でお試し中 4b962912e45020ccb3274ce45d00c1f76f3d40e8

**Comment by zk-phi** [comment]
analytics 見てもいい感じに伝わってそうなので閉じ
