### ISSUE TITLE
横長絵文字のサンプル表示

### ISSUE THREAD

**Issue by himantotopuhu** [zk-phi/MEGAMOJI#337]
現在の絵文字プレビューのサンプル表示では、横に長い絵文字が32*32pxまで縮小されて表示されます。
しかし、Misskeyなどのプラットフォームでは横に長い絵文字をそのまま横に長く表示することができます。
このような用途で使う用に、サンプル表示で大きさをキープできる機能が欲しいです。
よろしくお願いします。

**Comment by zk-phi** [comment]
修正しました🙌

**Comment by FineArchs** [comment]
ありがとうございます！
