### ISSUE TITLE
アニメーション非対応の環境でも文字を読めるようにしたい

### ISSUE THREAD

**Issue by hata6502** [zk-phi/MEGAMOJI#339]
Slackでは、アクセシビリティの機能によってアニメーションをOFFにできます。
[![Image from Gyazo](https://i.gyazo.com/a875c50082e981878387a5ccf3a7193b.png)](https://gyazo.com/a875c50082e981878387a5ccf3a7193b)

しかしアニメーションをOFFにすると、「カベドン」効果などを付けた絵文字を読めなくなります。
最初の1コマを表示する仕様のためです。
[![Image from Gyazo](https://i.gyazo.com/b6b8150f9bda386f8c2c27ca0c494d2f.png)](https://gyazo.com/b6b8150f9bda386f8c2c27ca0c494d2f)

アニメーション非対応の環境でも文字を読めるようにしたいです。

***

誰でも絵文字を作れるサービスを開発してくださり、ありがとうございます。
オープンソースとして公開されていることを知り、感激しました。

**Comment by zk-phi** [comment]
これは盲点でした :pray: ご指摘ありがとうございました！
