### ISSUE TITLE
空白がトリミングされないようにして欲しい

### ISSUE THREAD

**Issue by FineArchs** [zk-phi/MEGAMOJI#343]
現状だと、テキストでたとえば`　絵文字　`などと入力すると、左右の空白が除去されて`絵文字`として解釈されます。
左右の余白を調整するのに負のトリミングを指定するよりは空白を使うほうが直感的な場合もあるので、出来れば左右の空白は残しておいて欲しいです。

**Comment by zk-phi** [comment]
canvas の仕様上、描画されたテキストの幅を取得できないので、ピクセルのデータから直接算出する実装になっています。
空白が意図した空白なのかそうでないのか、判定できないため、スペースを残すことは難しいです。

それはそれとして、負のトリミングを設定するのは確かに直感的ではないので、パディングを設定する機能を実装しました。
