### ISSUE TITLE
「ドヘタ字 J」がライセンス上使えないが、使える状態になってしまっている

### ISSUE THREAD

**Issue by 1STEP621** [zk-phi/MEGAMOJI#344]
[「ドヘタ字 J」のBooth](https://booth.pm/ja/items/809142)に、
> ※制作頒布元であるかえるぴょん工房が公式に行うもの以外の下記行為は禁止とさせていただきます。
・フォントファイルの改変・複製・販売・二次配布
・**LINE絵文字など文字主体の制作物の配布・販売**
・フォントを使用した制作物の商標登録、意匠登録
・作者の許可なく素材集などへ収録して販売すること

という記述が追加されていました。
Wayback Machineを見ると、少なくとも2023/4/10以降に追加されたようです。
ダウンロードデータのreadme.txtにはそのような記述はなく、やや書いてあることが異なるようですが、絵文字として自由に利用できるフォントだけを収録するという方針であれば取り除いたほうがいいかもしれません。

**Comment by zk-phi** [comment]
ご報告ありがとうございます！対応しました :+1:
